name: Build-Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v2
        id: setup-ndk
        with:
          ndk-version: r21e

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1.1.5
        with:
          haxe-version: 4.2.5

      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp
          haxelib install lime 7.9.0
          haxelib install openfl 9.1.0

          # Flixel direto do GitHub (evita travar no Haxelib)
          haxelib git flixel https://github.com/HaxeFlixel/flixel 5.6.1

          haxelib install flixel-ui
          haxelib install flixel-addons

          haxelib git polymod https://github.com/MasterEric/polymod
          haxelib git linc_luajit https://github.com/MAJigsaw77/linc_luajit
          haxelib git extension-webm https://github.com/Sirox228/extension-webm
          haxelib git extension-webview https://github.com/MatheusSilver/extension-webview

      - name: Configure Lime
        run: |
          haxelib run lime setup -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
          haxelib run lime config JAVA_HOME $JAVA_HOME

          # Android 7 até Android 15
          # API 24 = Android 7
          # API 34 = Android 14/15
          haxelib run lime config ANDROID_MIN_SDK 24
          haxelib run lime config ANDROID_TARGET_SDK 34

      - name: Build APK
        run: |
          haxelib run lime build android -release --app-version="4.0.${{ github.run_id }}"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-Android-Build
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk
