name: Android Build (FNF Engine)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Haxe Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 8.0.2
          haxelib install openfl 9.2.2
          haxelib install hxcpp
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hxdiscord_rpc
          haxelib install linc_luajit

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Install Android SDK / NDK
        run: |
          sdkmanager "platforms;android-33" "build-tools;33.0.0"
          sdkmanager "ndk;23.1.7779620"

      - name: Configure Lime for Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_SDK_ROOT
          haxelib run lime config ANDROID_NDK $ANDROID_SDK_ROOT/ndk/23.1.7779620
          haxelib run lime config JAVA_HOME $JAVA_HOME

      - name: Build APK
        run: |
          haxelib run lime build android -release -clean

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: FNF-Android-Build
          path: export/release/android/bin/app-release.apk
